version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: url_db
    environment:
      POSTGRES_USER: url_db_admin
      POSTGRES_PASSWORD: url_db_admin
      POSTGRES_DB: url_db
    ports:
      - "5432:5432"

  url_lib:
    build:
      context: ../
    ports:
    - "8001:8000"
    depends_on:
    - postgres-db
    environment:
      DB_HOST: "url_db"
      DB_NAME: "url_db"
      DB_USER: "url_db_admin"
      DB_PASSWORD: "url_db_admin"
      DB_PORT: 5432

  nginx:
    image: nginx:latest
    depends_on:
      - url_lib
    volumes:
      - ../conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

